export declare function getBlockHeaderSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    nonce?: boolean | undefined;
    sha3Uncles?: boolean | undefined;
    logsBloom?: boolean | undefined;
    transactionsRoot?: boolean | undefined;
    stateRoot?: boolean | undefined;
    receiptsRoot?: boolean | undefined;
    mixHash?: boolean | undefined;
    miner?: boolean | undefined;
    difficulty?: boolean | undefined;
    totalDifficulty?: boolean | undefined;
    extraData?: boolean | undefined;
    size?: boolean | undefined;
    gasLimit?: boolean | undefined;
    gasUsed?: boolean | undefined;
    timestamp?: boolean | undefined;
    baseFeePerGas?: boolean | undefined;
    l1BlockNumber?: boolean | undefined;
}, {
    nonce?: boolean | null | undefined;
    sha3Uncles?: boolean | null | undefined;
    logsBloom?: boolean | null | undefined;
    transactionsRoot?: boolean | null | undefined;
    stateRoot?: boolean | null | undefined;
    receiptsRoot?: boolean | null | undefined;
    mixHash?: boolean | null | undefined;
    miner?: boolean | null | undefined;
    difficulty?: boolean | null | undefined;
    totalDifficulty?: boolean | null | undefined;
    extraData?: boolean | null | undefined;
    size?: boolean | null | undefined;
    gasLimit?: boolean | null | undefined;
    gasUsed?: boolean | null | undefined;
    timestamp?: boolean | null | undefined;
    baseFeePerGas?: boolean | null | undefined;
    l1BlockNumber?: boolean | null | undefined;
}>;
export declare function getTxSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    nonce?: boolean | undefined;
    hash?: boolean | undefined;
    type?: boolean | undefined;
    gasUsed?: boolean | undefined;
    sighash?: boolean | undefined;
    from?: boolean | undefined;
    to?: boolean | undefined;
    gas?: boolean | undefined;
    gasPrice?: boolean | undefined;
    maxFeePerGas?: boolean | undefined;
    maxPriorityFeePerGas?: boolean | undefined;
    input?: boolean | undefined;
    value?: boolean | undefined;
    v?: boolean | undefined;
    r?: boolean | undefined;
    s?: boolean | undefined;
    yParity?: boolean | undefined;
    chainId?: boolean | undefined;
    authorizationList?: boolean | undefined;
    cumulativeGasUsed?: boolean | undefined;
    effectiveGasPrice?: boolean | undefined;
    contractAddress?: boolean | undefined;
    status?: boolean | undefined;
    l1Fee?: boolean | undefined;
    l1FeeScalar?: boolean | undefined;
    l1GasPrice?: boolean | undefined;
    l1GasUsed?: boolean | undefined;
    l1BlobBaseFee?: boolean | undefined;
    l1BlobBaseFeeScalar?: boolean | undefined;
    l1BaseFeeScalar?: boolean | undefined;
}, {
    nonce?: boolean | null | undefined;
    hash?: boolean | null | undefined;
    type?: boolean | null | undefined;
    gasUsed?: boolean | null | undefined;
    sighash?: boolean | null | undefined;
    from?: boolean | null | undefined;
    to?: boolean | null | undefined;
    gas?: boolean | null | undefined;
    gasPrice?: boolean | null | undefined;
    maxFeePerGas?: boolean | null | undefined;
    maxPriorityFeePerGas?: boolean | null | undefined;
    input?: boolean | null | undefined;
    value?: boolean | null | undefined;
    v?: boolean | null | undefined;
    r?: boolean | null | undefined;
    s?: boolean | null | undefined;
    yParity?: boolean | null | undefined;
    chainId?: boolean | null | undefined;
    authorizationList?: boolean | null | undefined;
    cumulativeGasUsed?: boolean | null | undefined;
    effectiveGasPrice?: boolean | null | undefined;
    contractAddress?: boolean | null | undefined;
    status?: boolean | null | undefined;
    l1Fee?: boolean | null | undefined;
    l1FeeScalar?: boolean | null | undefined;
    l1GasPrice?: boolean | null | undefined;
    l1GasUsed?: boolean | null | undefined;
    l1BlobBaseFee?: boolean | null | undefined;
    l1BlobBaseFeeScalar?: boolean | null | undefined;
    l1BaseFeeScalar?: boolean | null | undefined;
}>;
export declare function getLogSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    address?: boolean | undefined;
    transactionHash?: boolean | undefined;
    data?: boolean | undefined;
    topics?: boolean | undefined;
}, {
    address?: boolean | null | undefined;
    transactionHash?: boolean | null | undefined;
    data?: boolean | null | undefined;
    topics?: boolean | null | undefined;
}>;
export declare function getTraceSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    createFrom?: boolean | undefined;
    createGas?: boolean | undefined;
    createValue?: boolean | undefined;
    createInit?: boolean | undefined;
    createResultCode?: boolean | undefined;
    createResultAddress?: boolean | undefined;
    createResultGasUsed?: boolean | undefined;
    callFrom?: boolean | undefined;
    callGas?: boolean | undefined;
    callValue?: boolean | undefined;
    callSighash?: boolean | undefined;
    callTo?: boolean | undefined;
    callInput?: boolean | undefined;
    callCallType?: boolean | undefined;
    callResultGasUsed?: boolean | undefined;
    callResultOutput?: boolean | undefined;
    suicideAddress?: boolean | undefined;
    suicideBalance?: boolean | undefined;
    suicideRefundAddress?: boolean | undefined;
    rewardValue?: boolean | undefined;
    rewardType?: boolean | undefined;
    rewardAuthor?: boolean | undefined;
    subtraces?: boolean | undefined;
    error?: boolean | undefined;
    revertReason?: boolean | undefined;
}, {
    createFrom?: boolean | null | undefined;
    createGas?: boolean | null | undefined;
    createValue?: boolean | null | undefined;
    createInit?: boolean | null | undefined;
    createResultCode?: boolean | null | undefined;
    createResultAddress?: boolean | null | undefined;
    createResultGasUsed?: boolean | null | undefined;
    callFrom?: boolean | null | undefined;
    callGas?: boolean | null | undefined;
    callValue?: boolean | null | undefined;
    callSighash?: boolean | null | undefined;
    callTo?: boolean | null | undefined;
    callInput?: boolean | null | undefined;
    callCallType?: boolean | null | undefined;
    callResultGasUsed?: boolean | null | undefined;
    callResultOutput?: boolean | null | undefined;
    suicideAddress?: boolean | null | undefined;
    suicideBalance?: boolean | null | undefined;
    suicideRefundAddress?: boolean | null | undefined;
    rewardValue?: boolean | null | undefined;
    rewardType?: boolean | null | undefined;
    rewardAuthor?: boolean | null | undefined;
    subtraces?: boolean | null | undefined;
    error?: boolean | null | undefined;
    revertReason?: boolean | null | undefined;
}>;
export declare function getStateDiffSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    kind?: boolean | undefined;
    prev?: boolean | undefined;
    next?: boolean | undefined;
}, {
    kind?: boolean | null | undefined;
    prev?: boolean | null | undefined;
    next?: boolean | null | undefined;
}>;
export declare function getFieldSelectionValidator(): import("@subsquid/util-internal-validation").Validator<{
    block?: {
        nonce?: boolean | undefined;
        sha3Uncles?: boolean | undefined;
        logsBloom?: boolean | undefined;
        transactionsRoot?: boolean | undefined;
        stateRoot?: boolean | undefined;
        receiptsRoot?: boolean | undefined;
        mixHash?: boolean | undefined;
        miner?: boolean | undefined;
        difficulty?: boolean | undefined;
        totalDifficulty?: boolean | undefined;
        extraData?: boolean | undefined;
        size?: boolean | undefined;
        gasLimit?: boolean | undefined;
        gasUsed?: boolean | undefined;
        timestamp?: boolean | undefined;
        baseFeePerGas?: boolean | undefined;
        l1BlockNumber?: boolean | undefined;
    } | undefined;
    log?: {
        address?: boolean | undefined;
        transactionHash?: boolean | undefined;
        data?: boolean | undefined;
        topics?: boolean | undefined;
    } | undefined;
    transaction?: {
        nonce?: boolean | undefined;
        hash?: boolean | undefined;
        type?: boolean | undefined;
        gasUsed?: boolean | undefined;
        sighash?: boolean | undefined;
        from?: boolean | undefined;
        to?: boolean | undefined;
        gas?: boolean | undefined;
        gasPrice?: boolean | undefined;
        maxFeePerGas?: boolean | undefined;
        maxPriorityFeePerGas?: boolean | undefined;
        input?: boolean | undefined;
        value?: boolean | undefined;
        v?: boolean | undefined;
        r?: boolean | undefined;
        s?: boolean | undefined;
        yParity?: boolean | undefined;
        chainId?: boolean | undefined;
        authorizationList?: boolean | undefined;
        cumulativeGasUsed?: boolean | undefined;
        effectiveGasPrice?: boolean | undefined;
        contractAddress?: boolean | undefined;
        status?: boolean | undefined;
        l1Fee?: boolean | undefined;
        l1FeeScalar?: boolean | undefined;
        l1GasPrice?: boolean | undefined;
        l1GasUsed?: boolean | undefined;
        l1BlobBaseFee?: boolean | undefined;
        l1BlobBaseFeeScalar?: boolean | undefined;
        l1BaseFeeScalar?: boolean | undefined;
    } | undefined;
    trace?: {
        createFrom?: boolean | undefined;
        createGas?: boolean | undefined;
        createValue?: boolean | undefined;
        createInit?: boolean | undefined;
        createResultCode?: boolean | undefined;
        createResultAddress?: boolean | undefined;
        createResultGasUsed?: boolean | undefined;
        callFrom?: boolean | undefined;
        callGas?: boolean | undefined;
        callValue?: boolean | undefined;
        callSighash?: boolean | undefined;
        callTo?: boolean | undefined;
        callInput?: boolean | undefined;
        callCallType?: boolean | undefined;
        callResultGasUsed?: boolean | undefined;
        callResultOutput?: boolean | undefined;
        suicideAddress?: boolean | undefined;
        suicideBalance?: boolean | undefined;
        suicideRefundAddress?: boolean | undefined;
        rewardValue?: boolean | undefined;
        rewardType?: boolean | undefined;
        rewardAuthor?: boolean | undefined;
        subtraces?: boolean | undefined;
        error?: boolean | undefined;
        revertReason?: boolean | undefined;
    } | undefined;
    stateDiff?: {
        kind?: boolean | undefined;
        prev?: boolean | undefined;
        next?: boolean | undefined;
    } | undefined;
}, {
    block?: {
        nonce?: boolean | null | undefined;
        sha3Uncles?: boolean | null | undefined;
        logsBloom?: boolean | null | undefined;
        transactionsRoot?: boolean | null | undefined;
        stateRoot?: boolean | null | undefined;
        receiptsRoot?: boolean | null | undefined;
        mixHash?: boolean | null | undefined;
        miner?: boolean | null | undefined;
        difficulty?: boolean | null | undefined;
        totalDifficulty?: boolean | null | undefined;
        extraData?: boolean | null | undefined;
        size?: boolean | null | undefined;
        gasLimit?: boolean | null | undefined;
        gasUsed?: boolean | null | undefined;
        timestamp?: boolean | null | undefined;
        baseFeePerGas?: boolean | null | undefined;
        l1BlockNumber?: boolean | null | undefined;
    } | null | undefined;
    log?: {
        address?: boolean | null | undefined;
        transactionHash?: boolean | null | undefined;
        data?: boolean | null | undefined;
        topics?: boolean | null | undefined;
    } | null | undefined;
    transaction?: {
        nonce?: boolean | null | undefined;
        hash?: boolean | null | undefined;
        type?: boolean | null | undefined;
        gasUsed?: boolean | null | undefined;
        sighash?: boolean | null | undefined;
        from?: boolean | null | undefined;
        to?: boolean | null | undefined;
        gas?: boolean | null | undefined;
        gasPrice?: boolean | null | undefined;
        maxFeePerGas?: boolean | null | undefined;
        maxPriorityFeePerGas?: boolean | null | undefined;
        input?: boolean | null | undefined;
        value?: boolean | null | undefined;
        v?: boolean | null | undefined;
        r?: boolean | null | undefined;
        s?: boolean | null | undefined;
        yParity?: boolean | null | undefined;
        chainId?: boolean | null | undefined;
        authorizationList?: boolean | null | undefined;
        cumulativeGasUsed?: boolean | null | undefined;
        effectiveGasPrice?: boolean | null | undefined;
        contractAddress?: boolean | null | undefined;
        status?: boolean | null | undefined;
        l1Fee?: boolean | null | undefined;
        l1FeeScalar?: boolean | null | undefined;
        l1GasPrice?: boolean | null | undefined;
        l1GasUsed?: boolean | null | undefined;
        l1BlobBaseFee?: boolean | null | undefined;
        l1BlobBaseFeeScalar?: boolean | null | undefined;
        l1BaseFeeScalar?: boolean | null | undefined;
    } | null | undefined;
    trace?: {
        createFrom?: boolean | null | undefined;
        createGas?: boolean | null | undefined;
        createValue?: boolean | null | undefined;
        createInit?: boolean | null | undefined;
        createResultCode?: boolean | null | undefined;
        createResultAddress?: boolean | null | undefined;
        createResultGasUsed?: boolean | null | undefined;
        callFrom?: boolean | null | undefined;
        callGas?: boolean | null | undefined;
        callValue?: boolean | null | undefined;
        callSighash?: boolean | null | undefined;
        callTo?: boolean | null | undefined;
        callInput?: boolean | null | undefined;
        callCallType?: boolean | null | undefined;
        callResultGasUsed?: boolean | null | undefined;
        callResultOutput?: boolean | null | undefined;
        suicideAddress?: boolean | null | undefined;
        suicideBalance?: boolean | null | undefined;
        suicideRefundAddress?: boolean | null | undefined;
        rewardValue?: boolean | null | undefined;
        rewardType?: boolean | null | undefined;
        rewardAuthor?: boolean | null | undefined;
        subtraces?: boolean | null | undefined;
        error?: boolean | null | undefined;
        revertReason?: boolean | null | undefined;
    } | null | undefined;
    stateDiff?: {
        kind?: boolean | null | undefined;
        prev?: boolean | null | undefined;
        next?: boolean | null | undefined;
    } | null | undefined;
}>;
//# sourceMappingURL=selection.d.ts.map